#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm log.pitzdailytutorial && rm -r 0.1/ 0.2/ 0.3/ 0.4/ 0.5/

